language: node_js
node_js:
  - lts/*

branches:
  only:
  - master

cache:
  yarn: true
  directories:
  - node_modules

before_script:
  - yarn upgrade

install:
  - yarn install

script:
  - yarn test
